
apiVersion: v1
kind: Service
metadata:
  labels:
    app: urs-stats
    app.kubernetes.io/instance: urs-stats
  name: urs-stats
  namespace: ingress-nginx
spec:
  ports:
    - name: http-web
      port: 8020
      protocol: TCP
      targetPort: 8020
    - name: https-portal
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: urs-stats
  type: ClusterIP
